FROM scratch

COPY dist/ /dynamic-plugins/dist/
COPY LICENSE /licenses/LICENSE

LABEL version="0.0.2-dev" \
      com.redhat.component="rhcl-rhdh-dynamic-plugin-container" \
      name="rhcl-1/rhcl-rhdh-dynamic-plugin-rhel9" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      summary="Red Hat Connectivity Link RHDH Dynamic Plugins" \
      description="Backstage dynamic plugins for Red Hat Connectivity Link" \
      io.k8s.display-name="Red Hat Connectivity Link RHDH Dynamic Plugins" \
      io.openshift.tags="api" \
      io.k8s.description="" \
      maintainer="eastizle@redhat.com"

USER 1001
